"""Tests for the paper converter module.

Covers:
- ``clean_text`` post-processing
- ``MarkdownSource`` from .md files
- ``PmcXmlSource`` from JATS XML
- ``Pymupdf4llmSource`` (import/instantiation only — integration requires optional dep)
- ``PaperInsights`` integration
- CLI argument handling
"""

import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

from core.ai.prompts import (
    PAPER_FIGURE_SYSTEM_PROMPT,
    PAPER_META_SYSTEM_PROMPT,
    PAPER_METHODS_SYSTEM_PROMPT,
)
from core.paper.converter import (
    MarkdownSource,
    PaperSource,
    PmcXmlSource,
    Pymupdf4llmSource,
    clean_text,
)
from core.paper.insights import (
    PaperInsights,
    _extract_data_access,
    _extract_geo_ids,
    _extract_key_methods,
    _extract_methods_summary,
    _parse_filename_meta,
)

# ── Fixture paths ────────────────────────────────────────────────────────────

FIXTURE_DIR = Path(__file__).parent.parent / "fixtures"
PMC_FIXTURE = FIXTURE_DIR / "pmc114514.xml"
PAPERS_DIR = Path("projects/papers")
FAKE_MD = PAPERS_DIR / "2020_Doe_FakeJCell_Fictional-SingleCell-Study.md"

# ── pytest skip conditions ───────────────────────────────────────────────────

_PYMUPDF4LLM_AVAILABLE: bool = False
try:
    import pymupdf4llm  # noqa: F401

    _PYMUPDF4LLM_AVAILABLE = True
except ImportError:
    pass

skipif_no_pymupdf4llm = pytest.mark.skipif(
    not _PYMUPDF4LLM_AVAILABLE,
    reason="pymupdf4llm not installed (pip install -r requirements/paper.txt)",
)

skipif_pymupdf4llm = pytest.mark.skipif(
    _PYMUPDF4LLM_AVAILABLE,
    reason="pymupdf4llm is installed — can't test import-error path",
)

_HAS_PMC_FIXTURE: bool = PMC_FIXTURE.exists()
skipif_no_pmc_fixture = pytest.mark.skipif(
    not _HAS_PMC_FIXTURE,
    reason="PMC fixture unavailable — skipping PMC XML integration tests",
)


# ═════════════════════════════════════════════════════════════════════════════
#  1.  clean_text
# ═════════════════════════════════════════════════════════════════════════════


class TestCleanText:
    """Post-processing text-cleanup function."""

    def test_lower_upper_boundary(self) -> None:
        """Lowercase followed by uppercase: ``ofAMD`` → ``of AMD``."""
        assert clean_text("ofAMD") == "of AMD"

    def test_period_upper_boundary(self) -> None:
        """Period followed by uppercase: ``elderly.However`` → ``elderly. However``."""
        assert clean_text("elderly.However") == "elderly. However"

    def test_known_false_positive(self) -> None:
        """Known false-positive: ``snRNA-seq`` → ``sn RNA-seq``."""
        result = clean_text("snRNA-seq")
        # The module documents this specific false-positive case
        assert "sn" in result
        assert "RNA" in result or "RNA" in result

    def test_identity_preserving(self) -> None:
        """Already-clean text should be unchanged (modulo trailing whitespace)."""
        text = "This is clean text with normal spacing."
        assert clean_text(text) == text

    def test_multiple_whitespace_collapsed(self) -> None:
        """Extra spaces between words are collapsed to one."""
        assert clean_text("word1   word2    word3") == "word1 word2 word3"

    def test_newlines_collapsed(self) -> None:
        """Three or more consecutive newlines collapse to exactly two."""
        text = "para1\n\n\n\npara2"
        assert clean_text(text) == "para1\n\npara2"

    def test_multiple_newlines_collapsed(self) -> None:
        """Four consecutive newlines become two (paragraph separator)."""
        text = "a\n\n\n\n\nb"
        assert clean_text(text) == "a\n\nb"


# ═════════════════════════════════════════════════════════════════════════════
#  2.  MarkdownSource
# ═════════════════════════════════════════════════════════════════════════════


class TestMarkdownSource:
    """Parse a real .md paper file."""

    @pytest.fixture
    def fake_source(self) -> MarkdownSource:
        return MarkdownSource(str(FAKE_MD))

    def test_init_sections(self, fake_source: MarkdownSource) -> None:
        """A real .md file should produce at least 4 section keys."""
        sections = fake_source.get_sections()
        assert len(sections) >= 4
        # Synthetic test fixture — most sections generated by parser defaults
        assert "abstract" in sections
        assert "introduction" in sections
        assert "results" in sections
        assert "discussion" in sections
        assert "methods" in sections

    def test_methods_content(self, fake_source: MarkdownSource) -> None:
        """The methods section should have substantial content."""
        sections = fake_source.get_sections()
        methods_text = sections.get("methods", "")
        assert len(methods_text) > 1000, "Methods section should have >1000 chars"

    def test_figures(self, fake_source: MarkdownSource) -> None:
        """A real .md file should extract multiple figure blocks."""
        figures = fake_source.get_figure_blocks()
        assert len(figures) >= 3, f"Expected ≥3 figure blocks, got {len(figures)}"

    def test_metadata(self, fake_source: MarkdownSource) -> None:
        """Filename-derived metadata should include year/author/journal."""
        meta = fake_source.get_metadata()
        assert meta["year"] == "2020"
        assert meta["first_author"] == "Doe"
        assert meta["journal"] == "FakeJCell"
        assert "filename" in meta

    def test_empty_file(self) -> None:
        """Empty string should not crash — produce empty sections."""
        tmp = FIXTURE_DIR / "_empty_test.md"
        try:
            tmp.write_text("", encoding="utf-8")
            src = MarkdownSource(str(tmp))
            sections = src.get_sections()
            assert isinstance(sections, dict)
            assert len(sections) >= 4
            figures = src.get_figure_blocks()
            assert isinstance(figures, list)
        finally:
            if tmp.exists():
                tmp.unlink()

    def test_no_headers(self) -> None:
        """Text without section headers should place all content in ``results``."""
        tmp = FIXTURE_DIR / "_noheader_test.md"
        try:
            tmp.write_text("Some plain text without any headers.", encoding="utf-8")
            src = MarkdownSource(str(tmp))
            sections = src.get_sections()
            assert sections.get("results", "").strip() != ""
        finally:
            if tmp.exists():
                tmp.unlink()


# ═════════════════════════════════════════════════════════════════════════════
#  3.  PmcXmlSource
# ═════════════════════════════════════════════════════════════════════════════


class TestPmcXmlSource:
    """Parse a real JATS XML from PMC."""

    def test_init_no_args_raises(self) -> None:
        """No arguments should raise ValueError."""
        with pytest.raises(ValueError, match="Provide at least one"):
            PmcXmlSource()

    @skipif_no_pmc_fixture
    def test_from_fixture(self) -> None:
        """Load from XML fixture — sections, figures, metadata present."""
        src = PmcXmlSource(xml_path=str(PMC_FIXTURE))
        sections = src.get_sections()
        assert "abstract" in sections or "introduction" in sections
        assert "results" in sections
        assert "methods" in sections

        figures = src.get_figure_blocks()
        assert len(figures) >= 3, f"Expected ≥3 figures, got {len(figures)}"

        meta = src.get_metadata()
        assert meta.get("pmid") is not None
        assert meta.get("doi") is not None
        assert meta.get("title") is not None
        assert meta.get("first_author") is not None
        assert meta.get("year") is not None

    @skipif_no_pmc_fixture
    def test_metadata_values(self) -> None:
        """Verify metadata values from synthetic PMC XML fixture."""
        src = PmcXmlSource(xml_path=str(PMC_FIXTURE))
        meta = src.get_metadata()
        assert meta["doi"] == "10.1234/synthetic-2024-00001"
        assert meta["year"] == "2024"
        assert meta["first_author"] == "Smith"
        assert meta["pmid"] == "114514"
        assert "title" in meta and len(meta["title"]) > 20

    @skipif_no_pmc_fixture
    def test_paper_name(self) -> None:
        src = PmcXmlSource(xml_path=str(PMC_FIXTURE))
        name = src.get_paper_name()
        assert "114514" in name and "2024_Smith" in name, f"Unexpected paper name: {name}"
        assert "Synthetic_Single_Cell" in name
        # Ensure filesystem-safe: no special chars
        assert re.match(r"^[\w_]+$", name), f"Paper name not filesystem-safe: {name}"

    @skipif_no_pmc_fixture
    def test_get_text(self) -> None:
        """Full text should concatenate all sections with double newlines."""
        src = PmcXmlSource(xml_path=str(PMC_FIXTURE))
        text = src.get_text()
        assert len(text) > 1000
        assert "\n\n" in text

    def test_invalid_path_raises(self) -> None:
        """Non-existent XML path should raise."""
        with pytest.raises((RuntimeError, FileNotFoundError)):
            PmcXmlSource(xml_path="/nonexistent/path/to/file.xml")

    @skipif_no_pmc_fixture
    def test_sections_contain_keywords(self) -> None:
        """Section content should contain relevant keywords."""
        src = PmcXmlSource(xml_path=str(PMC_FIXTURE))
        sections = src.get_sections()
        results_text = sections.get("results", "")
        # The results section should contain retina/AMD-related terms
        assert "retina" in results_text.lower() or "cell" in results_text.lower()
        assert len(results_text) > 500


# ═════════════════════════════════════════════════════════════════════════════
#  4.  Pymupdf4llmSource
# ═════════════════════════════════════════════════════════════════════════════


class TestPymupdf4llmSource:
    """Optional PDF source — import test only (needs pymupdf4llm)."""

    def test_class_importable(self) -> None:
        """Class can be imported without ImportError from module level."""
        # Import succeeds at module top; instantiation is what fails
        from core.paper.converter import Pymupdf4llmSource as Cls  # noqa: F811

        assert Cls is not None

    @skipif_pymupdf4llm
    def test_instantiation_raises_import_error(self) -> None:
        """Instantiating without pymupdf4llm should raise ImportError."""
        with pytest.raises(ImportError, match="pymupdf4llm not installed"):
            Pymupdf4llmSource("dummy.pdf")

    @skipif_no_pymupdf4llm
    def test_pdf_source_with_pymupdf4llm(self) -> None:
        """If pymupdf4llm IS installed, constructing with a real PDF works.

        This test is skipped unless pymupdf4llm is available.
        """
        # Find a PDF in the test fixtures or papers directory
        md_stem = FAKE_MD.stem
        pdf_candidates = [
            PAPERS_DIR / f"{md_stem}.pdf",
            PAPERS_DIR / md_stem / f"{md_stem}.pdf",
        ]
        for pdf in pdf_candidates:
            if pdf.exists():
                src = Pymupdf4llmSource(str(pdf))
                assert src.get_sections() is not None
                return
        pytest.skip("No PDF fixture available for integration test")


# ═════════════════════════════════════════════════════════════════════════════
#  5.  Integration tests (PaperInsights + sources)
# ═════════════════════════════════════════════════════════════════════════════


class _FakeLLMConfig:
    """Minimal config stub to let PaperInsights methods run without real LLM."""

    model = "test-model"
    api_base = "http://test"
    api_key = "test-key"
    max_tokens = 256
    temperature = 0.0
    ai_cache_responses = False
    thinking_enabled = False


class TestPaperInsights:
    """Integration between PaperInsights and PaperSource classes."""

    @pytest.fixture
    def cfg(self) -> _FakeLLMConfig:
        return _FakeLLMConfig()

    def test_merge_to_insights_custom_meta(self, cfg: _FakeLLMConfig) -> None:
        """Pass custom paper_meta dict → appears in output."""
        insights = PaperInsights.merge_to_insights(
            meta={"experimental_design": {"species": "human"}, "key_findings": ["test"]},
            figures=[{"id": "Fig1", "description": "test figure"}],
            methods_data={"data_notes": ["note1"]},
            paper_meta={"custom_key": "custom_value"},
        )
        assert insights["paper_meta"]["custom_key"] == "custom_value"
        assert "key_findings" in insights
        assert "figures" in insights
        assert "reproduction_status" in insights

    def test_merge_to_insights_deduplicates_figures(self, cfg: _FakeLLMConfig) -> None:
        """Duplicate figure IDs should be removed."""
        insights = PaperInsights.merge_to_insights(
            meta={},
            figures=[
                {"id": "Fig1", "desc": "first"},
                {"id": "Fig1", "desc": "duplicate"},
                {"id": "Fig2", "desc": "unique"},
            ],
            methods_data={},
            paper_meta={},
        )
        assert len(insights["figures"]) == 2

    def test_parse_filename_meta(self) -> None:
        """_parse_filename_meta extracts year/author/journal from filename."""
        meta = _parse_filename_meta(str(FAKE_MD))
        assert meta["year"] == "2020"
        assert meta["first_author"] == "Doe"
        assert meta["journal"] == "FakeJCell"
        assert meta["title"] == "Fictional-SingleCell-Study"

    def test_split_sections_known_pattern(self) -> None:
        """split_sections returns expected keys."""
        text = (
            "Abstract\nThis is the abstract.\n"
            "Introduction\nThis is intro.\n"
            "Results\nThese are results.\n"
            "Discussion\nDiscussion text.\n"
            "Methods\nMethod details."
        )
        sections = PaperInsights.split_sections(text)
        assert "abstract" in sections
        assert "introduction" in sections
        assert "results" in sections
        assert "discussion" in sections
        assert "methods" in sections

    def test_split_sections_no_headers(self) -> None:
        """Text with no recognized headers → all content in results."""
        sections = PaperInsights.split_sections("Just some plain text with no headers.")
        assert sections["results"] == "Just some plain text with no headers."

    def test_extract_figure_blocks(self) -> None:
        """Figure blocks split correctly from results text."""
        text = (
            "Some intro text. Figure 1. This is the first figure. "
            "Figure 2. This is the second figure."
        )
        blocks = PaperInsights.extract_figure_blocks(text)
        assert len(blocks) == 2
        assert "Figure 1" in blocks[0]
        assert "Figure 2" in blocks[1]

    def test_extract_figure_blocks_empty(self) -> None:
        """Empty text returns empty list."""
        assert PaperInsights.extract_figure_blocks("") == []

    def test_output_yaml_structure(self) -> None:
        """The merge_to_insights output has the expected top-level keys."""
        insights = PaperInsights.merge_to_insights(
            meta={},
            figures=[],
            methods_data={},
            paper_meta={"year": "2020", "first_author": "Doe"},
        )
        expected_keys = {
            "paper_meta",
            "experimental_design",
            "key_findings",
            "data_access",
            "methods",
            "data_notes",
            "figures",
            "reproduction_status",
        }
        assert set(insights.keys()) == expected_keys

    def test_merge_to_insights_methods_propagation(self) -> None:
        """Verify methods_data propagates key_methods, software_versions, etc."""
        insights = PaperInsights.merge_to_insights(
            meta={},
            figures=[],
            methods_data={
                "key_methods": ["Seurat", "CellRanger"],
                "software_versions": {"Seurat": "4.0"},
                "reference_genome": "hg38",
                "sequencing_platforms": ["NovaSeq 6000"],
                "data_notes": ["some note"],
            },
            paper_meta={},
        )
        assert "methods" in insights
        assert insights["methods"]["key_methods"] == ["Seurat", "CellRanger"]
        assert insights["methods"]["software_versions"] == {"Seurat": "4.0"}
        assert insights["methods"]["reference_genome"] == "hg38"
        assert insights["methods"]["sequencing_platforms"] == ["NovaSeq 6000"]


# ═════════════════════════════════════════════════════════════════════════════
#  11.  New regex-fallback helpers (_extract_geo_ids, _extract_key_methods, etc.)
# ═════════════════════════════════════════════════════════════════════════════


class TestExtractGeoIds:
    """Tests for _extract_geo_ids regex helper."""

    def test_extracts_gse(self) -> None:
        """Extracts GSE accession from text."""
        assert _extract_geo_ids("GSE12345 is the accession") == ["GSE12345"]

    def test_multiple_gse(self) -> None:
        """Extracts multiple GSE accessions."""
        result = _extract_geo_ids("GSE12345 and GSE67890 are both here")
        assert result == ["GSE12345", "GSE67890"]

    def test_variable_length(self) -> None:
        """Supports 4-8 digit GSE IDs."""
        assert _extract_geo_ids("GSE1234") == ["GSE1234"]
        assert _extract_geo_ids("GSE12345678") == ["GSE12345678"]

    def test_no_false_positive_partial(self) -> None:
        """Does not match GSE without digits."""
        assert _extract_geo_ids("not a GSE here") == []

    def test_empty_text(self) -> None:
        """Empty string returns empty list."""
        assert _extract_geo_ids("") == []


class TestExtractDataAccess:
    """Tests for _extract_data_access with full_text fallback."""

    def test_primary_path(self) -> None:
        """meta.data_access is used as primary source."""
        meta = {"data_access": {"geo_ids": ["GSE12345"], "sra_ids": []}}
        result = _extract_data_access(meta, None)
        assert result["geo_ids"] == ["GSE12345"]

    def test_fallback_full_text_regex(self) -> None:
        """When primary and data_notes empty, scans full_text for GEO IDs."""
        result = _extract_data_access({}, {}, full_text="GSE99999 is the accession")
        assert "GSE99999" in result["geo_ids"]

    def test_no_fallback_when_geo_already_found(self) -> None:
        """Does not scan full_text when geo_ids already populated by primary path."""
        meta = {"data_access": {"geo_ids": ["GSE11111"]}}
        result = _extract_data_access(meta, {}, full_text="GSE99999")
        assert result["geo_ids"] == ["GSE11111"]  # should NOT add GSE99999

    def test_empty_full_text_skips_fallback(self) -> None:
        """Empty full_text means no regex scan occurs."""
        result = _extract_data_access({}, {})
        assert result["geo_ids"] == []

    def test_sra_ids_extracted_from_data_notes(self) -> None:
        """SRA IDs extracted from data_notes fallback path."""
        meta = {"data_notes": ["SRP12345 is here"]}
        result = _extract_data_access(meta, {})
        assert "SRP12345" in result["sra_ids"]


class TestExtractKeyMethods:
    """Tests for _extract_key_methods regex helper."""

    def test_known_method_detected(self) -> None:
        """Detects UMAP in text via keyword matching."""
        result = _extract_key_methods("We used UMAP for visualization")
        assert "UMAP" in result

    def test_multiple_methods(self) -> None:
        """Detects multiple methods preserving order of appearance."""
        result = _extract_key_methods("We used Seurat and Harmony for integration, then UMAP")
        assert result == ["Seurat", "Harmony", "UMAP"]

    def test_case_insensitive(self) -> None:
        """Matches case-insensitively: 'seurat' matches 'Seurat'."""
        result = _extract_key_methods("We used seurat for analysis")
        assert "Seurat" in result

    def test_word_boundary_prevents_substring(self) -> None:
        """'SeuratDisk' does not match 'Seurat' keyword (word boundary)."""
        result = _extract_key_methods("We used SeuratDisk for loading")
        assert "Seurat" not in result

    def test_no_methods_found(self) -> None:
        """Text with no known methods returns empty list."""
        result = _extract_key_methods("This paper does not mention any known method.")
        assert result == []

    def test_empty_text(self) -> None:
        """Empty string returns empty list."""
        assert _extract_key_methods("") == []


class TestExtractMethodsSummary:
    """Tests for _extract_methods_summary with full_text fallback."""

    def test_methods_data_used_when_provided(self) -> None:
        """When methods_data has key_methods, they are used directly."""
        result = _extract_methods_summary({"key_methods": ["Seurat"]})
        assert result["key_methods"] == ["Seurat"]

    def test_empty_methods_data_returns_structured_empty(self) -> None:
        """When methods_data is None/empty, returns structured empty result."""
        result = _extract_methods_summary(None)
        assert result["key_methods"] == []
        assert result["software_versions"] == {}
        assert result["reference_genome"] is None
        assert result["sequencing_platforms"] == []

    def test_fallback_full_text_when_key_methods_empty(self) -> None:
        """When key_methods empty after LLM, falls back to regex on full_text."""
        result = _extract_methods_summary(
            {"key_methods": []}, full_text="We used UMAP for visualization"
        )
        assert "UMAP" in result["key_methods"]

    def test_fallback_full_text_when_methods_none(self) -> None:
        """When methods_data is None, falls back to regex on full_text."""
        result = _extract_methods_summary(None, full_text="We used Seurat and Harmony")
        assert result["key_methods"] == ["Seurat", "Harmony"]

    def test_no_fallback_when_key_methods_already_populated(self) -> None:
        """Does not fall back when key_methods already populated by LLM."""
        result = _extract_methods_summary(
            {"key_methods": ["CustomMethod"]}, full_text="We used UMAP"
        )
        assert result["key_methods"] == ["CustomMethod"]  # should NOT add UMAP

    def test_software_versions_preserved(self) -> None:
        """Non-key_methods fields from methods_data are preserved after fallback."""
        result = _extract_methods_summary(
            {
                "key_methods": [],
                "software_versions": {"Seurat": "4.0"},
                "reference_genome": "hg38",
                "sequencing_platforms": ["NovaSeq"],
            },
            full_text="We used UMAP",
        )
        assert "UMAP" in result["key_methods"]
        assert result["software_versions"] == {"Seurat": "4.0"}
        assert result["reference_genome"] == "hg38"
        assert result["sequencing_platforms"] == ["NovaSeq"]


class TestSplitSectionsMaterialsAndMethods:
    """Tests for split_sections with Materials and Methods heading and pre-heading abstract."""

    def test_materials_and_methods_mapped_to_methods(self) -> None:
        """'Materials and Methods' heading maps to 'methods' key."""
        text = "Abstract\nAbstract text.\nMaterials and Methods\nMethod details."
        sections = PaperInsights.split_sections(text)
        assert sections["methods"] == "Method details."

    def test_materials_and_methods_with_ampersand(self) -> None:
        """'Materials & Methods' heading also maps to 'methods' key."""
        text = "Abstract\nAbstract text.\nMaterials & Methods\nMethod details."
        sections = PaperInsights.split_sections(text)
        assert sections["methods"] == "Method details."

    def test_pre_heading_text_captured_as_abstract(self) -> None:
        """Text before first heading is captured as abstract when no Abstract heading."""
        text = "This is the introductory text that serves as abstract.\nIntroduction\nIntro text."
        sections = PaperInsights.split_sections(text)
        assert "This is the introductory text that serves as abstract." in sections["abstract"]

    def test_abstract_heading_takes_precedence(self) -> None:
        """Explicit Abstract heading takes precedence over pre-heading text."""
        text = "Pre-header intro.\nAbstract\nReal abstract text.\nIntroduction\nIntro text."
        sections = PaperInsights.split_sections(text)
        assert "Real abstract text." in sections["abstract"]
        assert "Pre-header intro." not in sections["abstract"]

    def test_markdown_heading_syntax(self) -> None:
        """Markdown ## heading syntax works for new headings."""
        text = "## Materials and Methods\nMethod content here."
        sections = PaperInsights.split_sections(text)
        assert sections["methods"] == "Method content here."


class TestReproductionStatus:
    """Tests for reproduction_status computation in merge_to_insights."""

    def test_reproduction_status_counts(self) -> None:
        """3 figures (2 reproducible=true, 1 false) → total_figures=3, reproducible_count=2."""
        figures = [
            {"id": "Fig1", "reproducible": True},
            {"id": "Fig2", "reproducible": True},
            {"id": "Fig3", "reproducible": False},
        ]
        insights = PaperInsights.merge_to_insights(
            meta={}, figures=figures, methods_data={}, paper_meta={}
        )
        rs = insights["reproduction_status"]
        assert rs["total_figures"] == 3
        assert rs["reproducible_count"] == 2

    def test_reproduction_status_empty(self) -> None:
        """Empty figures → total_figures=0, reproducible_count=0."""
        insights = PaperInsights.merge_to_insights(
            meta={}, figures=[], methods_data={}, paper_meta={}
        )
        rs = insights["reproduction_status"]
        assert rs["total_figures"] == 0
        assert rs["reproducible_count"] == 0

    def test_reproduction_status_still_has_tracking(self) -> None:
        """Tracking fields (pipeline_run, verified_figures) still present."""
        insights = PaperInsights.merge_to_insights(
            meta={}, figures=[], methods_data={}, paper_meta={}
        )
        rs = insights["reproduction_status"]
        assert "pipeline_run" in rs
        assert "verified_figures" in rs
        assert "notes" in rs


class TestEndToEnd:
    """End-to-end integration test for PaperInsights pipeline with mocked LLM calls."""

    def test_end_to_end_mock_merge(self, tmp_path: Path) -> None:
        """Mock LLM extraction outputs, merge via merge_to_insights, verify YAML output."""

        paper_meta = {
            "year": "2023",
            "first_author": "Test",
            "journal": "Test Journal",
            "doi": "10.1234/test",
        }

        meta = {
            "paper_type": "research",
            "experimental_design": {
                "species": "homo_sapiens",
                "tissue": "retina",
                "tissue_info": "",
                "models": [],
                "conditions": [],
                "modalities": ["snRNA-seq"],
                "summary": "Test summary.",
            },
            "key_findings": ["58 cell types identified"],
            "data_access": {"geo_ids": ["GSE137537"], "sra_ids": []},
            "data_notes": [],
        }

        figures = [
            {
                "id": "Fig_1",
                "caption": "UMAP embedding.",
                "type": "umap",
                "panels": ["1a"],
                "parameters": {
                    "features": [],
                    "resolution": None,
                    "method": None,
                    "conditions": [],
                    "n_value": None,
                    "error_bar_type": None,
                },
                "purpose": "UMAP overview.",
                "reproducible": True,
                "reproducibility_reasoning": "Computational visualization.",
            }
        ]

        methods_data = {
            "key_methods": ["10x Genomics", "CellRanger"],
            "software_versions": {"CellRanger": "7.0"},
            "reference_genome": "hg38",
            "sequencing_platforms": ["NovaSeq 6000"],
            "data_notes": [],
        }

        insights = PaperInsights.merge_to_insights(
            meta=meta,
            figures=figures,
            methods_data=methods_data,
            paper_meta=paper_meta,
        )

        # Write YAML
        yaml_path = tmp_path / "insights.yaml"
        with open(yaml_path, "w") as f:
            yaml.dump(insights, f, default_flow_style=False)

        # Verify YAML output
        assert yaml_path.exists(), f"YAML file not found at {yaml_path}"
        with open(yaml_path) as f:
            data = yaml.safe_load(f)

        assert "paper_meta" in data
        assert "experimental_design" in data
        assert "key_findings" in data
        assert "data_access" in data
        assert "methods" in data
        assert "figures" in data
        assert "data_notes" in data
        assert "reproduction_status" in data
        assert data["methods"]["key_methods"] == ["10x Genomics", "CellRanger"]
        assert data["reproduction_status"]["total_figures"] == 1
        assert data["reproduction_status"]["reproducible_count"] == 1


# ═════════════════════════════════════════════════════════════════════════════
#  6.  CLI tests
# ═════════════════════════════════════════════════════════════════════════════


class TestCli:
    """CLI argument handling for paper_insights.py."""

    CLI_SCRIPT = "core/paper/insights.py"

    def _run(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [sys.executable, self.CLI_SCRIPT, *args],
            capture_output=True,
            text=True,
        )

    def test_help_contains_new_params(self) -> None:
        """--help should list all CLI parameters."""
        result = self._run("--help")
        assert result.returncode == 0
        # Core params
        assert "--pmid" in result.stdout
        assert "--doi" in result.stdout
        assert "--xml" in result.stdout
        assert "--pdf" in result.stdout
        assert "--source" in result.stdout
        assert "--output" in result.stdout or "-o" in result.stdout
        assert "--force" in result.stdout or "-f" in result.stdout

    def test_mutual_exclusion_pmid_xml(self) -> None:
        """--pmid and --xml together should exit with error."""
        result = self._run("--pmid", "12345", "--xml", "/tmp/test.xml")
        assert result.returncode != 0
        assert "mutually exclusive" in result.stderr.lower()

    def test_positional_only_with_md_file(self) -> None:
        """Positional argument with an existing .md file works (returns non-zero
        only if LLM API key is missing, not because of argparse failure)."""
        if not FAKE_MD.exists():
            pytest.skip("Fake paper .md not found")
        self._run(str(FAKE_MD), "--help")  # just test parsing, use --help
        # Actually test positional-only mode: the script should parse without error
        # (it may fail later due to missing LLM key, but argparse should succeed)
        result2 = self._run(str(FAKE_MD))
        # The script might fail at runtime (missing LLM key), but shouldn't crash
        # with argparse error
        assert "usage:" not in result2.stderr.lower() or "error:" not in result2.stderr.lower()


# ═════════════════════════════════════════════════════════════════════════════
#  7.  Abstract base class
# ═════════════════════════════════════════════════════════════════════════════


class TestPaperSourceABC:
    """PaperSource abstract base class constraints."""

    def test_cannot_instantiate_directly(self) -> None:
        """PaperSource ABC cannot be instantiated."""
        with pytest.raises(TypeError):
            PaperSource()  # type: ignore[abstract]


# ═════════════════════════════════════════════════════════════════════════════
#  8.  PMC fixture validation
# ═════════════════════════════════════════════════════════════════════════════


@pytest.mark.skip(reason="PMC fixture removed — needs synthetic replacement")
class TestPmcFixture:
    """Validate the fixture file itself (skipped — fixture removed)."""

    def test_fixture_exists(self) -> None:
        """PMC fixture file should exist."""
        assert PMC_FIXTURE.exists(), (
            f"Synthetic PMC fixture not found at {PMC_FIXTURE}. "
            "This is a synthetic test fixture — "
            "regenerate if accidentally deleted."
        )

    def test_fixture_size_under_limit(self) -> None:
        """Fixture should be under 500KB."""
        assert PMC_FIXTURE.stat().st_size < 500 * 1024, "Fixture too large"
        assert PMC_FIXTURE.stat().st_size > 1000, "Fixture suspiciously small"

    def test_fixture_no_dtd(self) -> None:
        """Fixture should not contain DOCTYPE declaration (stripped for portability)."""
        content = PMC_FIXTURE.read_text(encoding="utf-8")
        assert "<!DOCTYPE" not in content, "Fixture should not contain DOCTYPE"

    def test_fixture_parses_as_xml(self) -> None:
        """Fixture should be valid XML parseable by xml.etree.ElementTree."""
        import xml.etree.ElementTree as ET

        root = ET.parse(str(PMC_FIXTURE)).getroot()
        assert root.tag == "article"
        assert root.find("body") is not None
        assert root.find("./front/article-meta") is not None


# ═════════════════════════════════════════════════════════════════════════════
#  9.  clean_text — new patterns (char-spacing, watermark, line-no, garbage)
# ═════════════════════════════════════════════════════════════════════════════


class TestCleanTextNewPatterns:
    """New clean_text patterns: char-spacing, watermark, line-number, garbage-char suppression."""

    def test_character_spacing_suppressed(self) -> None:
        """Character-spaced text: ``A u t h o r   M a n u s c r i p t`` → single letters."""
        result = clean_text("A u t h o r   M a n u s c r i p t")
        assert "A u" not in result

    def test_watermark_line_removed(self) -> None:
        """Watermark: ``Author Manuscript\ncontent`` → watermark line removed."""
        result = clean_text("Author Manuscript\nActual content")
        assert "Actual content" in result
        assert "Author Manuscript" not in result

    def test_leading_number_stripped(self) -> None:
        """Line number: ``42 Some text`` → ``Some text``."""
        result = clean_text("42 Some text")
        assert result == "Some text"

    def test_garbage_char_runs_removed(self) -> None:
        """Garbage runs: ``bbbbbbiiiiioooo text`` → `` text`` (garbage chars removed)."""
        result = clean_text("bbbbbbiiiiioooo text")
        assert "text" in result

    def test_single_letter_term_preserved(self) -> None:
        """Bioterm preserved: ``T cell receptor`` unchanged (not char-spacing)."""
        result = clean_text("T cell receptor")
        assert result == "T cell receptor"

    def test_hyphenated_bioterm_preserved(self) -> None:
        """Hyphenated bioterm: ``RNA-seq`` unchanged."""
        result = clean_text("RNA-seq")
        assert result == "RNA-seq"


# ═════════════════════════════════════════════════════════════════════════════
#  10.  System prompt content assertions
# ═════════════════════════════════════════════════════════════════════════════


class TestPromptContent:
    """Content assertions for redesigned system prompts."""

    def test_figure_prompt_contains_caption(self) -> None:
        """PAPER_FIGURE_SYSTEM_PROMPT should reference 'caption'."""
        assert "caption" in PAPER_FIGURE_SYSTEM_PROMPT

    def test_figure_prompt_has_stacked_violin(self) -> None:
        """PAPER_FIGURE_SYSTEM_PROMPT includes 'stacked_violin' in controlled vocabulary."""
        assert "stacked_violin" in PAPER_FIGURE_SYSTEM_PROMPT

    def test_figure_prompt_has_reproducibility_reasoning(self) -> None:
        """PAPER_FIGURE_SYSTEM_PROMPT includes 'reproducibility_reasoning'."""
        assert "reproducibility_reasoning" in PAPER_FIGURE_SYSTEM_PROMPT

    def test_meta_prompt_contains_paper_type(self) -> None:
        """PAPER_META_SYSTEM_PROMPT includes 'paper_type'."""
        assert "paper_type" in PAPER_META_SYSTEM_PROMPT

    def test_methods_prompt_contains_reference_genome(self) -> None:
        """PAPER_METHODS_SYSTEM_PROMPT includes 'reference_genome'."""
        assert "reference_genome" in PAPER_METHODS_SYSTEM_PROMPT

    def test_all_prompts_have_corrupted_input_instruction(self) -> None:
        """All system prompts contain 'artifacts' or 'ignore' for corrupted-input handling."""
        for name, prompt in [
            ("meta", PAPER_META_SYSTEM_PROMPT),
            ("figure", PAPER_FIGURE_SYSTEM_PROMPT),
            ("methods", PAPER_METHODS_SYSTEM_PROMPT),
        ]:
            assert "artifacts" in prompt or "ignore" in prompt, (
                f"{name} prompt missing 'artifacts' or 'ignore'"
            )

    def test_all_prompts_have_few_shot_example(self) -> None:
        """All system prompts contain 'EXAMPLE' or equivalent few-shot marker."""
        for name, prompt in [
            ("meta", PAPER_META_SYSTEM_PROMPT),
            ("figure", PAPER_FIGURE_SYSTEM_PROMPT),
            ("methods", PAPER_METHODS_SYSTEM_PROMPT),
        ]:
            assert "EXAMPLE" in prompt or "Example" in prompt, (
                f"{name} prompt missing few-shot example marker"
            )
