#!/usr/bin/env python3
"""
10X MTX (CellRanger output) config template — generic scRNA-seq
=================================================================
This template is for CellRanger filtered output directories containing:
  - barcodes.tsv.gz  (or .tsv)
  - features.tsv.gz  (or .tsv)
  - matrix.mtx.gz    (or .mtx)

Usage:
    Generated by Fuxi preprocessor.  Review and edit the sections
    marked with # TODO before running the pipeline.

    python core/run_pipeline.py --modality rna --config this_config.py
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
from core.config import CFG

# ── Data format ──
CFG.data_format = '10X_mtx'
CFG.mtx_prefix = '{{MTX_PREFIX}}'
CFG.mtx_dir = '{{MTX_DIR}}'

# ── Dataset metadata ──
CFG.tissue = '{{TISSUE}}'   # TODO: verify tissue type
CFG.species = '{{SPECIES}}'

# ── Sample mapping ──
# TODO: Map 10X barcode suffixes (-1, -2, ...) to sample names.
# CFG.sample_map = {
#     1: 'sample1',
#     2: 'sample2',
# }

# ── Stage mapping (if developmental data) ──
# TODO: Map sample barcode suffixes to developmental stages.
# CFG.stage_map = {
#     1: 'Day3',
#     2: 'Day7',
# }
# CFG.stage_order = ['Day3', 'Day7']

# ── QC ──
CFG.min_genes = 500
CFG.max_genes = 7500
CFG.max_pct_mito = 20.0
CFG.min_genes_per_umi = 0.7
CFG.run_scrublet = True

# ── HVG ──
CFG.n_top_genes = 4000
CFG.hvg_batch_key = 'sample'

# ── Batch correction ──
CFG.harmony_batch_key = 'sample'

# ── Clustering ──
CFG.leiden_resolutions = [0.3, 0.5, 0.8, 1.0, 1.5, 2.0]
CFG.best_resolution = 1.0
CFG.umap_min_dist = 0.3    # increase (e.g. 0.5) for more UMAP spread
CFG.umap_spread = 1.0

# ── Cell type markers ──
# TODO: Add known marker genes for {{TISSUE}} tissue.
CFG.marker_dict = {
    # 'CellTypeA': ['GENE1', 'GENE2', 'GENE3'],
    # 'CellTypeB': ['GENE4', 'GENE5', 'GENE6'],
}

# ── Knowledge base ──
# TODO: Set to a tissue KB name if one exists in rna/tissue_ontologies/.
CFG.tissue_kb = ''   # e.g. 'retina', 'hypothalamus'

# ── Subclustering ──
CFG.subcluster_types = []   # TODO: cell types to subcluster
CFG.subcluster_resolution = 0.4
CFG.min_cells_subcluster = 50

# ── Trajectory ──
CFG.root_cell_types = []    # TODO: developmental root cell types
# Alternative: auto-detect root via marker genes
# CFG.root_markers = ['SOX2', 'PAX6', 'NES']

# ── Differential expression ──
CFG.de_method = 'wilcoxon'
CFG.de_n_genes = 50
CFG.de_pval_cutoff = 0.05
CFG.de_logfc_cutoff = 0.25

# ── AI settings (uncomment to enable) ──
# CFG.ai.enabled = True
# CFG.ai.api_base = 'https://api.deepseek.com/v1'
# CFG.ai.model = 'deepseek-v4-pro'
# CFG.ai.api_key = os.environ.get('LLM_API_KEY', '')
# CFG.ai.max_tokens = 32768
# CFG.ai.temperature = 0.1
# CFG.ai.thinking_enabled = True
# CFG.ai.reasoning_effort = 'high'
# CFG.ai.ai_annotation = True
# CFG.ai.ai_subcluster = True
# CFG.ai.ai_interpretation = True
# CFG.ai.ai_cache_responses = True

# ── Execution ──
CFG.n_jobs = 0   # auto-detect
CFG.random_seed = 42
