#!/usr/bin/env python3
"""
10X MTX (CellRanger output) config template — generic scRNA-seq
=================================================================
This template is for CellRanger filtered output directories containing:
  - barcodes.tsv.gz  (or .tsv)
  - features.tsv.gz  (or .tsv)
  - matrix.mtx.gz    (or .mtx)

Usage:
    Generated by Fuxi preprocessor.  Review and edit the sections
    marked with # TODO before running the pipeline.

    python core/run_pipeline.py --modality rna --config this_config.py
"""
import os
from core.config import CFG

# ── Data format ──
CFG.data_format = '10X_mtx'
CFG.mtx_prefix = '{{MTX_PREFIX}}'
# mtx_dir is auto-resolved from FUXI_DATA_ROOT/{dataset_id} in resolve_paths().
# Only set this explicitly if your data is in a non-standard location.
# CFG.mtx_dir = ''

# ── Dataset metadata ──
CFG.tissue = '{{TISSUE}}'   # TODO: verify tissue type
CFG.species = '{{SPECIES}}'
CFG.expression_type = '{{EXPRESSION_TYPE}}'   # raw_counts | TPM | log1p_counts | CPM | FPKM
# TPM/FPKM/CPM: total_counts & complexity filters are auto-skipped.
# Scrublet is auto-disabled for non-raw_counts data.
# Adjust min_genes / max_pct_mito accordingly.

# ── Sample mapping ──
# TODO: Map 10X barcode suffixes (-1, -2, ...) to sample names.
# CFG.sample_map = {
#     1: 'sample1',
#     2: 'sample2',
# }

# ── Stage mapping (if developmental data) ──
# TODO: Map sample barcode suffixes to developmental stages.
# CFG.stage_map = {
#     1: 'Day3',
#     2: 'Day7',
# }
# CFG.stage_order = ['Day3', 'Day7']

# ── QC ──
CFG.min_genes = 500
CFG.max_genes = 7500
CFG.max_pct_mito = 20.0
CFG.min_cells_per_gene = 3
CFG.run_scrublet = True           # auto-disabled when expression_type != "raw_counts"
CFG.min_genes_per_umi = 0.7       # complexity filter — only applied when expression_type="raw_counts"
# CFG.use_adaptive_thresholds = True   # 替代固定阈值，基于 MAD
# CFG.mad_n_mads = 3.0

# ── HVG ──
CFG.n_top_genes = 4000
CFG.hvg_batch_key = 'sample'
CFG.hvg_flavor = 'seurat_v3'
# CFG.use_regress_out = False     # 回归细胞周期/n_counts 等协变量

# ── Batch correction / Harmony ──
CFG.harmony_batch_key = 'sample'
CFG.use_harmony = True
CFG.harmony_max_iter = 20

# ── PCA ──
CFG.n_pcs_full = 100
CFG.n_pcs_use = 50

# ── Clustering ──
CFG.leiden_resolutions = [0.3, 0.5, 0.8, 1.0, 1.5, 2.0]
CFG.best_resolution = 1.0   # Only used when cluster_selection_method is None
CFG.best_n_neighbors = 0     # Only used when cluster_selection_method is None; 0 = auto-pick
CFG.cluster_selection_method = "pareto_elbow"  # "pareto_elbow" | "silhouette" | None
# UMAP visualization parameter sweep — tried AFTER best cluster params selected.
# Selection method:  "convex_hull" (auto, default) | None (manual: use umap_min_dist/spread)
CFG.umap_selection_method = "convex_hull"
CFG.param_grid_min_dist = [0.1, 0.3, 0.5]  # values to sweep
CFG.param_grid_spread = [1.0]
CFG.umap_min_dist = 0.3    # increase (e.g. 0.5) for more UMAP spread
CFG.umap_spread = 1.0

# ── Cell type markers ──
# TODO: Add known marker genes for {{TISSUE}} tissue.
CFG.marker_dict = {
    # 'CellTypeA': ['GENE1', 'GENE2', 'GENE3'],
    # 'CellTypeB': ['GENE4', 'GENE5', 'GENE6'],
}

# ── Knowledge base ──
# TODO: Set to a tissue KB name if one exists in rna/tissue_ontologies/.
CFG.tissue_kb = ''   # e.g. 'retina', 'hypothalamus'

# ── Subclustering ──
CFG.subcluster_types = []   # TODO: cell types to subcluster
CFG.subcluster_resolution = 0.4
CFG.min_cells_subcluster = 50

# ── Trajectory ──
CFG.root_cell_types = []    # TODO: developmental root cell types
# Alternative: auto-detect root via marker genes
# CFG.root_markers = ['SOX2', 'PAX6', 'NES']
# CFG.n_diffmap_comps = 15
# CFG.n_branchings = 2

# ── Differential expression ──
CFG.de_method = 'wilcoxon'
CFG.de_n_genes = 50
CFG.de_pval_cutoff = 0.05
CFG.de_logfc_cutoff = 0.25
CFG.de_stage_pairwise = True
# CFG.de_auto_switch_on_low_quality = True   # 低质量数据自动切换方法

# ── Enrichment (uncomment to enable) ──
# CFG.run_enrichment = True
# CFG.enrichment_method = 'both'     # 'ora' | 'prerank' | 'both'
# CFG.enrichment_gene_sets = ['GO_Biological_Process_2023', 'KEGG_2021_Human']
# CFG.enrichment_organism = 'human'

# ── GRN regulatory network analysis (uncomment to enable) ──
CFG.run_grn = True
CFG.grn_method = "decoupler"         # 'decoupler' only for now (pySCENIC TBD)
CFG.grn_species = "human"            # 'human' | 'mouse'
CFG.grn_n_top_regulons = 50          # top N variable TFs for heatmap
CFG.grn_min_regulon_size = 5         # minimum target genes per regulon
# CFG.grn_confidence_levels = ["A", "B", "C"]  # DoRothEA confidence levels

# ── CCI 细胞通讯分析 (取消注释以启用) ──
CFG.run_cci = True
# CFG.cci_method = "liana"                  # 'liana' (LIANA+ rank_aggregate)
# CFG.cci_lr_database = "consensus"         # 'consensus' | 'cellphonedb' | 'cellchat' | 'celltalkdb' | 'ramilowski'
# CFG.cci_permutations = 1000               # permutation 迭代次数
# CFG.cci_n_top_interactions = 50           # 热图展示的 top 互作对数量
# CFG.cci_spatial_method = "liana_spatial"  # spatial 方法 (reserves 'commot')
# CFG.cci_spatial_distance = 0.0            # 0 = use existing spatial_connectivities
# CFG.cci_lr_cache_dir = ""                 # LIANA cache 目录; 空 = auto (~/.cache/liana)
# # CFG.cci_multi_condition = False         # future: multi-condition CCI

# ── AI settings (uncomment to enable) ──
# CFG.ai.enabled = True
# CFG.ai.api_base = 'https://api.deepseek.com/v1'
# CFG.ai.model = 'deepseek-v4-pro'
# CFG.ai.api_key = os.environ.get('LLM_API_KEY', '')
# CFG.ai.max_tokens = 32768
# CFG.ai.temperature = 0.1
# CFG.ai.thinking_enabled = True
# CFG.ai.reasoning_effort = 'high'
# CFG.ai.ai_annotation = True
# CFG.ai.ai_subcluster = True
# CFG.ai.ai_interpretation = True
# CFG.ai.ai_cache_responses = True

# ── Execution ──
CFG.n_jobs = 0   # auto-detect
CFG.random_seed = 42
# CFG.force_csr = True           # 强制 CSR 稀疏矩阵格式
# CFG.use_float32 = False        # 使用 float32 减少内存
# CFG.limit_blas_threads = True  # 限制 BLAS 线程数
# CFG.scanpy_verbosity = 2       # Scanpy 日志级别 (0=error, 1=warning, 2=info)
# CFG.h5ad_compression = 'gzip'  # h5ad 写入压缩

# ── Downsampling (optional) ──
# CFG.downsample_target = 5000         # 每样本最多保留 N 细胞
# CFG.downsample_strategy = 'sample'   # 'sample' | 'random'
